import type {
  ActivityItem,
  FinanceSurfaceSpec,
  SourceItem,
  WorkspaceSnapshot,
} from "./types";

const freshness = {
  dataThrough: "2026-07-17T08:00:00+12:00",
  status: "current" as const,
  timezone: "Pacific/Auckland",
};

export const livingBriefSurface: FinanceSurfaceSpec = {
  specVersion: "FinanceSurfaceSpec@1",
  surfaceId: "surface_koru_living_brief",
  surfaceType: "living_brief",
  title: "Morning close",
  subtitle: "Three items need your attention",
  freshness,
  blocks: [
    {
      blockId: "block_koru_close_summary",
      type: "narrative",
      text: "The close finished from 10 bank rows. One pending Figma row was held out as a likely duplicate. The 30-day plan dips below the protected reserve after the planned laptop purchase.",
      tone: "caution",
    },
    {
      blockId: "block_koru_current_balance",
      type: "metric",
      label: "Cleared balance",
      valueMinor: 504576,
      currency: "NZD",
      evidenceIds: ["evd_koru_bank_csv"],
    },
    {
      blockId: "block_koru_projected_low",
      type: "metric",
      label: "Projected 30-day low",
      valueMinor: 190077,
      currency: "NZD",
      evidenceIds: ["evd_koru_forecast_30d"],
    },
    {
      blockId: "block_koru_missing_receipt",
      type: "finding",
      findingId: "finding_koru_missing_receipt",
      severity: "attention",
      title: "Mitre 10 needs context",
      summary: "NZD 184.75 is unresolved and has no receipt attached.",
      amountMinor: 18475,
      currency: "NZD",
      status: "open",
      evidenceIds: ["evd_koru_mitre10_row"],
    },
    {
      blockId: "block_koru_duplicate_pending",
      type: "finding",
      findingId: "finding_koru_duplicate_pending",
      severity: "info",
      title: "Pending Figma row held out",
      summary: "A NZD 30.00 pending row matches the posted Figma charge and is excluded from totals.",
      amountMinor: 3000,
      currency: "NZD",
      status: "open",
      evidenceIds: ["evd_koru_figma_posted", "evd_koru_figma_pending"],
    },
    {
      blockId: "block_koru_reserve_risk",
      type: "finding",
      findingId: "finding_koru_reserve_risk",
      severity: "critical",
      title: "Protected reserve is at risk",
      summary: "The projected low is NZD 99.23 below the NZD 2,000 reserve after the planned laptop purchase.",
      amountMinor: 9923,
      currency: "NZD",
      status: "open",
      evidenceIds: ["evd_koru_forecast_30d"],
    },
  ],
  actions: [
    {
      actionId: "act_koru_show_cash",
      type: "run_scenario",
      label: "Explore cash risk",
      scenarioId: "scenario_koru_laptop",
    },
    {
      actionId: "act_koru_open_sources",
      type: "open_drawer",
      label: "Open sources",
      drawer: "sources",
    },
    {
      actionId: "act_koru_open_activity",
      type: "open_drawer",
      label: "Open activity",
      drawer: "activity",
    },
  ],
};

export const cashScenarioSurface: FinanceSurfaceSpec = {
  specVersion: "FinanceSurfaceSpec@1",
  surfaceId: "surface_koru_cash_scenario",
  surfaceType: "cash_scenario",
  title: "30-day cash scenario",
  subtitle: "Planned laptop purchase on 7 August",
  freshness,
  blocks: [
    {
      blockId: "block_koru_cash_series",
      type: "cash_series",
      currency: "NZD",
      points: [
        { date: "2026-07-17", balanceMinor: 504576, reserveMinor: 200000, status: "above_reserve" },
        { date: "2026-07-28", balanceMinor: 629576, reserveMinor: 200000, status: "above_reserve" },
        { date: "2026-07-31", balanceMinor: 509576, reserveMinor: 200000, status: "above_reserve" },
        { date: "2026-08-03", balanceMinor: 500577, reserveMinor: 200000, status: "above_reserve" },
        { date: "2026-08-04", balanceMinor: 493077, reserveMinor: 200000, status: "above_reserve" },
        { date: "2026-08-07", balanceMinor: 193077, reserveMinor: 200000, status: "below_reserve" },
        { date: "2026-08-10", balanceMinor: 190077, reserveMinor: 200000, status: "below_reserve" },
      ],
      assumptions: [
        "The NZD 1,250 client payment arrives on 28 July.",
        "The NZD 3,000 laptop purchase is paid on 7 August.",
        "Rent and software recur on their listed dates; no unlisted income is assumed.",
      ],
      evidenceIds: ["evd_koru_bank_csv", "evd_koru_forecast_30d"],
    },
    {
      blockId: "block_koru_scenario_compare",
      type: "scenario_compare",
      baseline: {
        label: "With laptop",
        lowPointMinor: 190077,
        reserveShortfallMinor: 9923,
        currency: "NZD",
      },
      alternative: {
        label: "Defer laptop",
        lowPointMinor: 490077,
        reserveShortfallMinor: 0,
        currency: "NZD",
      },
      assumptions: ["Only the planned laptop timing changes."],
      evidenceIds: ["evd_koru_forecast_30d"],
    },
  ],
  actions: [
    {
      actionId: "act_koru_open_sources_cash",
      type: "open_drawer",
      label: "View assumptions",
      drawer: "sources",
    },
  ],
};

export const transactionDetailSurface: FinanceSurfaceSpec = {
  specVersion: "FinanceSurfaceSpec@1",
  surfaceId: "surface_koru_mitre_detail",
  surfaceType: "transaction_detail",
  title: "Mitre 10 Hamilton",
  subtitle: "15 July · unresolved · source-linked",
  freshness,
  blocks: [
    {
      blockId: "block_mitre_context",
      type: "narrative",
      text: "This NZD 184.75 card purchase is the only posted expense without enough context to classify. Tell me what it was for in your own words; I will keep your answer as an owner claim.",
      tone: "caution",
    },
    {
      blockId: "block_mitre_rows",
      type: "transaction_rows",
      rows: [
        {
          transactionId: "txn_koru_006",
          occurredOn: "2026-07-15",
          description: "MITRE 10 HAMILTON",
          amountMinor: -18475,
          currency: "NZD",
          status: "posted",
          classification: "unresolved",
          category: null,
          evidenceIds: ["evd_koru_mitre10_row"],
        },
      ],
      totalMinor: -18475,
      currency: "NZD",
    },
    {
      blockId: "block_mitre_sources",
      type: "source_list",
      sources: [
        {
          sourceItemId: "src_koru_bank_csv_20260717",
          label: "Koru Studio bank export — row 7",
          sourceType: "csv",
          receivedAt: "2026-07-17T07:59:00+12:00",
          status: "processed",
        },
      ],
    },
  ],
  actions: [
    {
      actionId: "act_mitre_sources",
      type: "focus_source",
      label: "Inspect source row",
      sourceItemId: "src_koru_bank_csv_20260717",
    },
  ],
};

export const recordsSurface: FinanceSurfaceSpec = {
  specVersion: "FinanceSurfaceSpec@1",
  surfaceId: "surface_koru_records",
  surfaceType: "records_table",
  title: "Prepared records",
  subtitle: "Posted transactions · 1–17 July",
  freshness,
  blocks: [
    {
      blockId: "block_records_summary",
      type: "narrative",
      text: "Nine posted rows are included. The pending Figma duplicate is held out and the Mitre 10 purchase remains unresolved until you add context.",
      tone: "neutral",
    },
    {
      blockId: "block_records_rows",
      type: "transaction_rows",
      rows: [
        {
          transactionId: "txn_koru_001",
          occurredOn: "2026-07-01",
          description: "Opening balance",
          amountMinor: 120000,
          currency: "NZD",
          status: "posted",
          classification: "transfer",
          category: "opening_balance",
          evidenceIds: ["evd_koru_bank_csv"],
        },
        {
          transactionId: "txn_koru_002",
          occurredOn: "2026-07-04",
          description: "Tui & Co design deposit",
          amountMinor: 725000,
          currency: "NZD",
          status: "posted",
          classification: "business",
          category: "client_income",
          evidenceIds: ["evd_koru_bank_csv"],
        },
        {
          transactionId: "txn_koru_004",
          occurredOn: "2026-07-08",
          description: "Studio rent",
          amountMinor: -120000,
          currency: "NZD",
          status: "posted",
          classification: "business",
          category: "rent",
          evidenceIds: ["evd_koru_bank_csv"],
        },
        {
          transactionId: "txn_koru_006",
          occurredOn: "2026-07-15",
          description: "Mitre 10 Hamilton",
          amountMinor: -18475,
          currency: "NZD",
          status: "posted",
          classification: "unresolved",
          category: null,
          evidenceIds: ["evd_koru_mitre10_row"],
        },
        {
          transactionId: "txn_koru_010",
          occurredOn: "2026-07-17",
          description: "Figma",
          amountMinor: -3000,
          currency: "NZD",
          status: "duplicate",
          classification: "business",
          category: "software",
          evidenceIds: ["evd_koru_figma_pending"],
        },
      ],
      totalMinor: 504576,
      currency: "NZD",
    },
  ],
  actions: [
    {
      actionId: "act_records_sources",
      type: "open_drawer",
      label: "Review source coverage",
      drawer: "sources",
    },
  ],
};

export const ownerPackSurface: FinanceSurfaceSpec = {
  specVersion: "FinanceSurfaceSpec@1",
  surfaceId: "surface_koru_owner_pack",
  surfaceType: "owner_pack",
  title: "Owner pack",
  subtitle: "Prepared from the same committed Daily Close",
  freshness,
  blocks: [
    {
      blockId: "block_owner_pack_intro",
      type: "narrative",
      text: "A concise handoff for Koru Studio: cleared cash, prepared income and expenses, unresolved evidence, cash assumptions, and the next owner action. This is bookkeeping preparation, not a tax filing or financial advice.",
      tone: "neutral",
    },
    {
      blockId: "block_owner_pack_html",
      type: "artifact_preview",
      artifactId: "artifact_koru_owner_pack_html",
      kind: "html",
      title: "Koru Studio owner pack — interactive preview",
      generatedAt: "2026-07-17T08:00:03+12:00",
      contentHash: "6f82cd96595aee376b11efb62c3cc52d8e8724b9647e4e4fcf894f1d55770651",
      downloadAvailable: true,
      evidenceIds: ["evd_koru_bank_csv", "evd_koru_forecast_30d"],
    },
    {
      blockId: "block_owner_pack_pdf",
      type: "artifact_preview",
      artifactId: "artifact_koru_owner_pack_pdf",
      kind: "pdf",
      title: "Koru Studio owner pack — PDF",
      generatedAt: "2026-07-17T08:00:03+12:00",
      contentHash: "dc0f89a8fcbdf717462730ac5fc3084ac47f35f8f5732921223cdef0647bc865",
      downloadAvailable: true,
      evidenceIds: ["evd_koru_bank_csv", "evd_koru_forecast_30d"],
    },
  ],
  actions: [
    {
      actionId: "act_download_owner_pack",
      type: "download_artifact",
      label: "Open PDF pack",
      artifactId: "artifact_koru_owner_pack_pdf",
      format: "pdf",
    },
  ],
};

export const correctedReceiptSurface: FinanceSurfaceSpec = {
  specVersion: "FinanceSurfaceSpec@1",
  surfaceId: "surface_koru_rule_receipt",
  surfaceType: "work_receipt",
  title: "Correction applied",
  subtitle: "A narrow, reversible rule now handles matching purchases",
  freshness,
  blocks: [
    {
      blockId: "block_rule_narrative",
      type: "narrative",
      text: "I recorded your explanation as an owner claim, classified this transaction as business / client fit-out materials, and created a rule limited to MITRE 10 purchases of NZD 500 or less. One existing transaction was affected.",
      tone: "positive",
    },
    {
      blockId: "block_rule_diff",
      type: "change_diff",
      eventId: "evt_koru_mitre_rule_created",
      changes: [
        { field: "classification", label: "Classification", before: "Unresolved", after: "Business" },
        { field: "category", label: "Category", before: null, after: "Client fit-out materials" },
        { field: "unresolvedExpenseMinor", label: "Unresolved expenses", before: 18475, after: 0 },
      ],
      evidenceIds: ["evd_koru_mitre10_row", "evd_koru_owner_claim_mitre"],
      undoAvailable: true,
    },
    {
      blockId: "block_rule_amount",
      type: "metric",
      label: "Transaction reclassified",
      valueMinor: 18475,
      currency: "NZD",
      evidenceIds: ["evd_koru_mitre10_row"],
    },
  ],
  actions: [
    {
      actionId: "act_undo_mitre_rule",
      type: "undo_event",
      label: "Undo correction",
      eventId: "evt_koru_mitre_rule_created",
    },
    {
      actionId: "act_rule_activity",
      type: "open_drawer",
      label: "View activity",
      drawer: "activity",
    },
  ],
};

export const undoneReceiptSurface: FinanceSurfaceSpec = {
  specVersion: "FinanceSurfaceSpec@1",
  surfaceId: "surface_koru_undo_receipt",
  surfaceType: "work_receipt",
  title: "Correction undone",
  subtitle: "History remains intact; the inverse event is now applied",
  freshness,
  blocks: [
    {
      blockId: "block_undo_narrative",
      type: "narrative",
      text: "The MITRE 10 rule is inactive and the transaction is unresolved again. The original correction and this inverse event remain in Activity for a complete audit trail.",
      tone: "neutral",
    },
    {
      blockId: "block_undo_diff",
      type: "change_diff",
      eventId: "evt_koru_mitre_rule_undone",
      changes: [
        { field: "classification", label: "Classification", before: "Business", after: "Unresolved" },
        { field: "category", label: "Category", before: "Client fit-out materials", after: null },
        { field: "unresolvedExpenseMinor", label: "Unresolved expenses", before: 0, after: 18475 },
      ],
      evidenceIds: ["evd_koru_mitre10_row", "evd_koru_owner_claim_mitre"],
      undoAvailable: false,
    },
  ],
  actions: [
    {
      actionId: "act_undo_activity",
      type: "open_drawer",
      label: "View audit trail",
      drawer: "activity",
    },
  ],
};

export const initialSources: SourceItem[] = [
  {
    sourceItemId: "src_koru_bank_csv_20260717",
    sourceType: "csv",
    label: "ANZ Everyday — CSV export",
    digest: "c2c07beeca632f4e09700837cc4b199653ce9b68f65b804b7c30e9838ef94eac",
    receivedAt: "2026-07-17T07:59:00+12:00",
    status: "linked",
    rowCount: 10,
  },
  {
    sourceItemId: "src_koru_akahu_anz_everyday",
    sourceType: "akahu",
    label: "Akahu · ANZ Everyday",
    digest: "a91f0c2e7b4d8e1f3056aa77cc4b199653ce9b68f65b804b7c30e9838ef94eac",
    receivedAt: "2026-07-17T08:10:00+12:00",
    status: "live",
    rowCount: 6,
  },
  {
    sourceItemId: "src_koru_telegram_910001",
    sourceType: "telegram_fixture",
    label: "Telegram · 1 prepared expense",
    digest: "58ec491e7cc4fcec630614b3db24da72986da10d0c52f813dfddfc101bc7e4a6",
    receivedAt: "2026-07-17T09:00:00+12:00",
    status: "pending",
    rowCount: 1,
  },
];

export const initialActivity: ActivityItem[] = [
  {
    activityId: "activity_koru_mitre_correction",
    kind: "finance_event",
    summary: "Mitre 10 correction",
    detail: "Unresolved → Client fit-out materials. Expense totals updated. Undo restores the previous guess.",
    status: "completed",
    occurredAt: "2026-07-17T08:12:00+12:00",
    undoable: true,
    eventId: "evt_koru_mitre_rule_created",
    evidenceIds: ["evd_koru_mitre10_row", "evd_koru_owner_claim_mitre"],
  },
  {
    activityId: "activity_koru_daily_close",
    kind: "job_run",
    summary: "Daily Close completed from 10 source rows",
    detail: "Ingested, normalised, classified, forecasted and prepared owner pack.",
    status: "completed",
    occurredAt: "2026-07-17T08:00:04+12:00",
    undoable: false,
    evidenceIds: ["evd_koru_bank_csv"],
  },
  {
    activityId: "activity_koru_akahu_sync",
    kind: "source_ingest",
    summary: "Akahu sync · ANZ Everyday",
    detail: "48 rows read through Open Banking. Password stayed with Akahu.",
    status: "completed",
    occurredAt: "2026-07-17T07:58:20+12:00",
    undoable: false,
    evidenceIds: ["evd_koru_akahu_anz"],
  },
];

export const workspaceFixture: WorkspaceSnapshot = {
  snapshotVersion: "api.snapshot@1",
  snapshotId: "snap_koru_after_close",
  workspace: {
    workspaceId: "ws_koru_studio",
    name: "Koru Studio",
    entityType: "nz_sole_trader",
    currency: "NZD",
    timezone: "Pacific/Auckland",
    protectedReserveMinor: 200000,
  },
  thread: {
    threadId: "thr_koru_studio_main",
    turns: [
      {
        turnId: "turn_koru_morning_close",
        role: "agent",
        content: "Morning close is complete. I held out one likely duplicate, found one expense that needs context, and the planned laptop takes cash NZD 99.23 below your protected reserve.",
        occurredAt: "2026-07-17T08:00:04+12:00",
        status: "complete",
        evidenceIds: [
          "evd_koru_bank_csv",
          "evd_koru_mitre10_row",
          "evd_koru_figma_pending",
          "evd_koru_forecast_30d",
        ],
      },
      {
        turnId: "turn_koru_agent_question",
        role: "agent",
        content: "What was the NZD 184.75 MITRE 10 purchase for? Answer however you naturally would—I will use what you tell me and keep the original source attached.",
        occurredAt: "2026-07-17T08:00:06+12:00",
        status: "complete",
        evidenceIds: ["evd_koru_mitre10_row"],
      },
    ],
    activeQuestion: {
      questionId: "question_koru_mitre_context",
      prompt: "What was the MITRE 10 purchase for?",
    },
  },
  currentSurface: livingBriefSurface,
  findings: [
    {
      findingId: "finding_koru_missing_receipt",
      kind: "missing_document",
      severity: "attention",
      title: "Mitre 10 needs context",
      summary: "NZD 184.75 is unresolved and has no receipt attached.",
      amountMinor: 18475,
      currency: "NZD",
      status: "open",
      evidenceIds: ["evd_koru_mitre10_row"],
    },
    {
      findingId: "finding_koru_duplicate_pending",
      kind: "duplicate",
      severity: "info",
      title: "Pending Figma row held out",
      summary: "The NZD 30.00 pending row matches the posted charge.",
      amountMinor: 3000,
      currency: "NZD",
      status: "open",
      evidenceIds: ["evd_koru_figma_posted", "evd_koru_figma_pending"],
    },
    {
      findingId: "finding_koru_reserve_risk",
      kind: "reserve_risk",
      severity: "critical",
      title: "Protected reserve is at risk",
      summary: "The 30-day low is NZD 99.23 below reserve.",
      amountMinor: 9923,
      currency: "NZD",
      status: "open",
      evidenceIds: ["evd_koru_forecast_30d"],
    },
  ],
  activity: initialActivity,
  sources: initialSources,
  totals: {
    asOf: "2026-07-17T08:00:00+12:00",
    currency: "NZD",
    currentBalanceMinor: 504576,
    protectedReserveMinor: 200000,
    businessIncomeMinor: 725000,
    businessExpenseMinor: 139499,
    personalExpenseMinor: 62450,
    unresolvedExpenseMinor: 18475,
    projectedLowPointMinor: 190077,
    reserveShortfallMinor: 9923,
  },
  artifacts: [
    {
      artifactId: "artifact_koru_owner_pack_html",
      kind: "owner_pack_html",
      title: "Koru Studio owner pack",
      contentHash: "6f82cd96595aee376b11efb62c3cc52d8e8724b9647e4e4fcf894f1d55770651",
      generatedAt: "2026-07-17T08:00:03+12:00",
      evidenceIds: ["evd_koru_bank_csv", "evd_koru_forecast_30d"],
    },
    {
      artifactId: "artifact_koru_owner_pack_pdf",
      kind: "owner_pack_pdf",
      title: "Koru Studio owner pack",
      contentHash: "dc0f89a8fcbdf717462730ac5fc3084ac47f35f8f5732921223cdef0647bc865",
      generatedAt: "2026-07-17T08:00:03+12:00",
      evidenceIds: ["evd_koru_bank_csv", "evd_koru_forecast_30d"],
    },
  ],
  modelMode: "local",
  freshness,
};

export const dailyCloseStages = [
  { key: "ingest", label: "Checking new sources" },
  { key: "normalise", label: "Normalising 10 rows" },
  { key: "rules", label: "Applying owner rules" },
  { key: "forecast", label: "Recomputing 30-day cash" },
  { key: "pack", label: "Preparing owner pack" },
] as const;
